//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanchesMac {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanchesMac.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir a categoria?.
        /// </summary>
        public static string CONFIRMA_DELECAO_CATEGORIA {
            get {
                return ResourceManager.GetString("CONFIRMA_DELECAO_CATEGORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir o lanche?.
        /// </summary>
        public static string CONFIRMA_DELECAO_LANCHE {
            get {
                return ResourceManager.GetString("CONFIRMA_DELECAO_LANCHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja excluir o pedido?.
        /// </summary>
        public static string CONFIRMA_DELECAO_PEDIDO {
            get {
                return ResourceManager.GetString("CONFIRMA_DELECAO_PEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string DESCRITIVO_CATEGORIA {
            get {
                return ResourceManager.GetString("DESCRITIVO_CATEGORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        public static string DESCRITIVO_CATEGORIA_PLURAL {
            get {
                return ResourceManager.GetString("DESCRITIVO_CATEGORIA_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Novo.
        /// </summary>
        public static string DESCRITIVO_CRIAR_NOVO {
            get {
                return ResourceManager.GetString("DESCRITIVO_CRIAR_NOVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar.
        /// </summary>
        public static string DESCRITIVO_DELETAR {
            get {
                return ResourceManager.GetString("DESCRITIVO_DELETAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string DESCRITIVO_DETALHES {
            get {
                return ResourceManager.GetString("DESCRITIVO_DETALHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string DESCRITIVO_EDITAR {
            get {
                return ResourceManager.GetString("DESCRITIVO_EDITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanche.
        /// </summary>
        public static string DESCRITIVO_LANCHE {
            get {
                return ResourceManager.GetString("DESCRITIVO_LANCHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanches.
        /// </summary>
        public static string DESCRITIVO_LANCHE_PLURAL {
            get {
                return ResourceManager.GetString("DESCRITIVO_LANCHE_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Categoria.
        /// </summary>
        public static string DESCRITIVO_NOVA_CATEGORIA {
            get {
                return ResourceManager.GetString("DESCRITIVO_NOVA_CATEGORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Lanche.
        /// </summary>
        public static string DESCRITIVO_NOVO_LANCHE {
            get {
                return ResourceManager.GetString("DESCRITIVO_NOVO_LANCHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Pedido.
        /// </summary>
        public static string DESCRITIVO_NOVO_PEDIDO {
            get {
                return ResourceManager.GetString("DESCRITIVO_NOVO_PEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string DESCRITIVO_PEDIDO {
            get {
                return ResourceManager.GetString("DESCRITIVO_PEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string DESCRITIVO_PEDIDO_PLURAL {
            get {
                return ResourceManager.GetString("DESCRITIVO_PEDIDO_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurar.
        /// </summary>
        public static string DESCRITIVO_PROCURAR {
            get {
                return ResourceManager.GetString("DESCRITIVO_PROCURAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string DESCRITIVO_SALVAR {
            get {
                return ResourceManager.GetString("DESCRITIVO_SALVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Pedidos.
        /// </summary>
        public static string DESCRITIVO_TOTAL_PEDIDOS {
            get {
                return ResourceManager.GetString("DESCRITIVO_TOTAL_PEDIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para Lista.
        /// </summary>
        public static string DESCRITVO_VOLTAR_LISTA {
            get {
                return ResourceManager.GetString("DESCRITVO_VOLTAR_LISTA", resourceCulture);
            }
        }
    }
}
